version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:alpine
    container_name: nats
    restart: always
    command: "-js"
    ports:
      - "4222:4222"

volumes:
  postgres_data:
